# @package _global_
xpd: ???

domain: ???

xp_overrides:
  datamodule:
    input_da: 
      _target_: src.utils.load_enatl
    domains:
      train:
        time: {_target_: builtins.slice , _args_: ['2010-02-24', '2010-07-31']}
      val: 
        time: {_target_: builtins.slice, _args_: ['2009-12-15', '2010-02-24']}
      test: 
        time: {_target_: builtins.slice,  _args_: ['2009-07-01', '2010-07-31']}
    xrds_kw:
      strides: {lat: 200, lon: 200}
      domain_limits: ${domain.train}
    dl_kw: {batch_size: 2, num_workers: 4}

## ==== With eNATL Data ====
xp_overrides_src:
  datamodule:
    input_da: 
      _target_: src.utils.load_enatl
    domains:
      train:
        time: {_target_: builtins.slice , _args_: ['2010-02-24', '2010-07-31']}
      val: 
        time: {_target_: builtins.slice, _args_: ['2009-12-15', '2010-02-24']}
      test: 
        time: {_target_: builtins.slice,  _args_: ['2009-07-01', '2010-07-31']}
    xrds_kw:
      strides: {lat: 200, lon: 200}
      domain_limits: ${src_domain.train}
    dl_kw: {batch_size: 2, num_workers: 4}

# ## ==== With NATL Data ====
# xp_overrides_src:
#   datamodule:
#     xrds_kw:
#       strides: {lat: 200, lon: 200}
#       domain_limits: ${src_domain.train}
#     dl_kw: {batch_size: 2, num_workers: 4}

test_periods: {"Octobre-December":["2009-10-22", "2009-12-02"]}

trainer: 
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  accelerator: gpu
  devices: 1
  logger: False

lit_mod:
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: model
  xpd : ${xpd}
  overrides: ${xp_overrides}

dm:
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: datamodule
  xpd : ${xpd}
  overrides: ${xp_overrides}

src_dm:
  _target_: contrib.multi_domain_diag.load_cfg_from_xp
  key: datamodule
  xpd : ${xpd}
  overrides: ${xp_overrides_src}

ckpt:
  _target_: src.utils.best_ckpt
  xp_dir: ${xpd}/base

test_domains: ???

rec_weight:
  _target_: contrib.multi_domain_diag.get_smooth_spat_rec_weight
  orig_rec_weight:
    _target_: contrib.multi_domain_diag.load_cfg_from_xp
    key: model.rec_weight
    xpd : ${xpd}

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: contrib.multi_domain_diag.multi_domain_osse_diag
    trainer: ${trainer}
    lit_mod: ${lit_mod}
    dm: ${dm}
    ckpt_path: ${ckpt}
    rec_weight: ${rec_weight}
    test_domains: ${test_domains}
    test_periods: ${test_periods}
    save_dir: ${hydra:runtime.output_dir}
    src_dm: ${src_dm}

defaults:
  - /domain: gf                  # prediction
  - /domain@src_domain: gf        # For normalize data

  # - /domain@test_domains.NATL: NATL
  # - /domain@test_domains.qnatl: qnatl
  # - /domain@test_domains.cNATL: cNATL
  # - /domain@test_domains.4gf: 4gf
  # - /domain@test_domains.2gf: 2gf
  - /domain@test_domains.gf: gf
  # - /domain@test_domains.canaries: canaries
  # - /domain@test_domains.osmosis: osmosis 
  # - /domain@test_domains.eNATL: eNATL
  # - /domain@test_domains.stage: stage
  - _self_